### ISSUE TITLE
Radio and checkbox borders missing

### ISSUE THREAD

**Issue by mfraser** [plasmazilla/mozilla-kde-support#11]
After the latest update unchecked checkboxes and radio icons are invisible. This makes it difficult to know where to click. Un-installing the plasmazilla version of Firefox shows these boxes again.

**Comment by shadeslayer** [comment]
Hi
Which version of Firefox is this? 47?

**Comment by cassiodoroVicinetti** [comment]
I confirm this issue.

Also scrollbars are not normal: they are completely gray, and no cursor is visible.

> ```
$ uname -a
Linux debian-luca 4.5.0-2-amd64 #1 SMP Debian 4.5.5-1 (2016-05-29) x86_64 GNU/Linux
```

> ```
$ plasmashell --version
plasmashell 5.6.4
```

> ```
$ apt-cache policy firefox-plasma
firefox-plasma:
  Installed: 1000~46.0.1+1-0+8+build16+wily
```

Firefox 47 is affected too.

**Comment by star-buck** [comment]
Thats likely because of firefox now using gtk3 themeing. Since gtk3 theming
breaks from minor release to minor release even in gnome3, its likely the
cause and needs adjustment in the used theme within plasma gtk
configuration or inside mozilla-kde-support package.

**Comment by llelectronics** [comment]
This might be actually the switch to gtk3 in firefox. Did you experience that also with the vanilla firefox packages?

**Comment by shadeslayer** [comment]
I can't reproduce this on my Debian systems here, and @llelectronics told me he can't reproduce it as well. Could you please provide screenshots?

**Comment by cassiodoroVicinetti** [comment]
Of course!

![checkbox](https://cloud.githubusercontent.com/assets/1621526/16090966/e36b8a52-3331-11e6-86ef-3b067b2516b5.png)
![scrollbar](https://cloud.githubusercontent.com/assets/1621526/16090969/e46f95ce-3331-11e6-888e-2e3240a15f0d.png)

Note: This is Firefox in safe mode (no add-ons).

**Comment by shadeslayer** [comment]
@cassiodoroVicinetti  And this happens without safe mode as well? Because we only test the patches against regular mode in Firefox.

**Comment by cassiodoroVicinetti** [comment]
Yes.

**Comment by shadeslayer** [comment]
Hi
I can't reproduce these issues :

![image](https://cloud.githubusercontent.com/assets/188976/16156944/bdf5f5f6-34b6-11e6-99c9-1ffd20779953.png)

![image](https://cloud.githubusercontent.com/assets/188976/16156956/d0d364e2-34b6-11e6-9d12-5fbb9af040e3.png)

**Comment by llelectronics** [comment]
@cassiodoroVicinetti
Please test a different gtk3 theme and see if it works after you set another one.

**Comment by cassiodoroVicinetti** [comment]
Unfortunately the GTK3 theme editor in the system settings does not seem to work. For example, I installed the `gnome-themes-standard` package, I selected "Adwaita" and I rebooted the system, but Evince looks the same as "Default".

**Comment by star-buck** [comment]
maybe theme is broken again, since gnome3/gtk3 is known to break with almost every .point release. So you need to make sure you installed a 3.20 compatible theme or since firefox started to use gtk3, make sure the theme matches the installed gtk3-libs?

**Comment by cassiodoroVicinetti** [comment]
@shadeslayer Which GTK3 theme is selected in your system settings?

**Comment by cassiodoroVicinetti** [comment]
So the GTK3 theme switcher in the system settings works.

I installed the `gtk3-engines-breeze` package and I selected the "Breeze" theme.

This is the result:
![checkbox](https://cloud.githubusercontent.com/assets/1621526/16170753/ff87fecc-355d-11e6-98bb-980b229254ef.png)
![scrollbar](https://cloud.githubusercontent.com/assets/1621526/16170754/05d8d2b0-355e-11e6-8443-cfbb95c97979.png)

- checkboxes are fixed
- scrollbars are better, but they still have issues
- buttons are broken

**Comment by cassiodoroVicinetti** [comment]
Oddly the "Breeze" theme is broken in a different way (checkboxes broken, scrollbars broken, buttons not broken) in GTK3 native applications.

Example: gedit

Theme "Default"
![gedit2](https://cloud.githubusercontent.com/assets/1621526/16170808/79e32f88-355f-11e6-8816-39ec57c7ba52.png)

Theme "Breeze"
![gedit4](https://cloud.githubusercontent.com/assets/1621526/16170818/c113007c-355f-11e6-8ae9-ca2d804eadf2.png)

Preferences - Theme "Default"
![gedit](https://cloud.githubusercontent.com/assets/1621526/16170804/649f65f6-355f-11e6-8a78-9926ed9f6103.png)

Preferences - Theme "Breeze"
![gedit3](https://cloud.githubusercontent.com/assets/1621526/16170806/6fad6768-355f-11e6-8ed5-ea5bb35787d2.png)

Closing dialog - Theme "Default"
![gedit7](https://cloud.githubusercontent.com/assets/1621526/16170829/fc19fd24-355f-11e6-9b02-9fe1eb03d68d.png)

Closing dialog - Theme "Breeze"
![gedit5](https://cloud.githubusercontent.com/assets/1621526/16170822/d7d2978c-355f-11e6-9db4-ac9ebf6cffcc.png)

**Comment by mfraser** [comment]
Using the Breeze theme instead the borders are now visible. To try to fix another problem I was having with Firefox, I started it from the command line. The first lines printed were:
(firefox:12397): Gtk-WARNING **: Theme directory actions/48 of theme breeze has no size field


(firefox:12397): Gtk-WARNING **: Theme directory categories/16 of theme breeze has no size field


(firefox:12397): Gtk-WARNING **: Theme directory categories/22 of theme breeze has no size field


(firefox:12397): Gtk-WARNING **: Theme directory categories/48 of theme breeze has no size field


(firefox:12397): Gtk-WARNING **: Theme directory devices/48 of theme breeze has no size field

Do these need fixing?

**Comment by llelectronics** [comment]
@mfraser This is a warning from the Breeze Icon theme. Just a warning so nothing that should break stuff.

**Comment by cassiodoroVicinetti** [comment]
Today `gtk3-engines-breeze` updated from 5.6.4-1 to 5.6.95-1. Now gedit is fixed, but Firefox is still broken in a different way (checkboxes broken, buttons ok, scrollbars partially broken).

**Comment by cassiodoroVicinetti** [comment]
Problem fixed with Firefox version 48.

**Comment by phgachoud** [comment]
Same problem still with firefox version 48...
[w3schools](http://www.w3schools.com/html/tryit.asp?filename=tryhtml_checkbox)

![firefoxrb](https://cloud.githubusercontent.com/assets/11555852/18840250/3f7bc6ea-840e-11e6-9364-be8e817ff20a.png)

**Comment by cassiodoroVicinetti** [comment]
@phgachoud Which is your `gtk3-engines-breeze` version?

**Comment by phgachoud** [comment]
dpkg -l|grep gtk3-engines-breeze gives nothing, how do I know that?

**Comment by cassiodoroVicinetti** [comment]
`apt-cache policy gtk3-engines-breeze`

**Comment by phgachoud** [comment]
```
 5.5.5-0ubuntu1 500
```

same problem with updated firefox 49
thx!

**Comment by cassiodoroVicinetti** [comment]
Your `gtk3-engines-breeze` package version is too old, so you need to wait for version at least 5.6.
